# Generated by Django 2.1.5 on 2019-02-02 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dialysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrno', models.TextField()),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_dialysis', models.IntegerField()),
                ('dry_wt', models.IntegerField()),
                ('reuse', models.IntegerField()),
                ('bloodtrans', models.IntegerField()),
                ('comordity', models.TextField()),
                ('heparin', models.IntegerField()),
                ('heparin_infusion', models.IntegerField()),
                ('esrd_cause', models.TextField()),
                ('dialysis_duration', models.IntegerField()),
                ('hbsAg', models.IntegerField()),
                ('antiHcv', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('sbpPre', models.IntegerField()),
                ('sbpPost', models.IntegerField()),
                ('dbpPre', models.IntegerField()),
                ('dbpPost', models.IntegerField()),
                ('pls1', models.IntegerField()),
                ('pls2', models.IntegerField()),
                ('rsp1', models.IntegerField()),
                ('rsp2', models.IntegerField()),
                ('wtPre', models.IntegerField()),
                ('wtPost', models.IntegerField()),
            ],
        ),
    ]
